// TP6-React_Angular/angular-auth-system/src/app/components/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: [],
  standalone: true,
  imports: [CommonModule],
})
export class DashboardComponent {
  constructor(private authService: AuthService) {}

  logout() {
    this.authService.logout();
  }
}

<div class="dashboard-container">
  <nav class="sidebar">
    <div class="sidebar-header">
      <img src="assets/enset_logo.png" alt="ENSET Logo" class="brand-logo" />
    </div>
    <ul class="sidebar-nav">
      <li class="nav-item active">Dashboard</li>
      <li class="nav-item">Products</li>
      <li class="nav-item">Upload File</li>
      <li class="nav-item">Settings</li>
    </ul>
  </nav>

  <main class="main-content">
    <div class="header-bar" style="margin-bottom: 2rem">
      <button class="btn btn-primary" (click)="logout()">Logout</button>
    </div>

    <div class="upload-section">
      <h2>Welcome to Dashboard</h2>
    </div>
  </main>
</div>

// TP6-React_Angular/react-auth-system/src/components/Dashboard.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { logout } from '../api/auth';
import logo from "../assets/enset_logo.png";


function Dashboard() {
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <div className="dashboard-container">
      <nav className="sidebar">
        <div className="sidebar-header">
          <img src={logo} alt="ENSET Logo" className="brand-logo" />
        </div>
        <ul className="sidebar-nav">
          <li className="nav-item active">Dashboard</li>
          <li className="nav-item">Products</li>
          <li className="nav-item">Upload File</li>
          <li className="nav-item">Settings</li>
        </ul>
      </nav>

      <main className="main-content">
        <div className="header-bar" style={{ marginBottom: '2rem' }}>
          <button className="btn btn-primary" onClick={handleLogout}>Logout</button>
        </div>
        
        <div className="upload-section">
          <h2>Welcome to Dashboard</h2>
        </div>
      </main>
    </div>
  );
}

export default Dashboard;
