// TP6-React_Angular/angular-auth-system/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: [],
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, RouterLink],
})
export class LoginComponent {
  loginForm: FormGroup;
  errorMessage: string = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', [Validators.required]],
      password: ['', Validators.required],
    });
  }

  onSubmit() {
    if (this.loginForm.valid) {
      const { username, password } = this.loginForm.value;
      this.authService.login(username, password).subscribe({
        next: () => this.router.navigate(['/dashboard']),
        error: () => (this.errorMessage = 'Invalid username or password'),
      });
    }
  }
}

<div class="auth-container">
  <div class="brand-section">
    <div class="brand-content">
      <img src="assets/enset_logo.png" alt="ENSET Logo" class="brand-logo" />
      <h1>ENSET</h1>
      <p>École Normale Supérieure de l'Enseignement Technique</p>
    </div>
  </div>

  <div class="form-section">
    <div class="auth-card">
      <div class="form-header">
        <img src="assets/enset_logo.png" alt="ENSET Logo" class="brand-logo" />
        <h2>User Login</h2>
      </div>
      <div class="form-body">
        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
          <div class="form-group">
            <div *ngIf="errorMessage" class="error-message">{{ errorMessage }}</div>
            <label class="form-label">Username</label>
            <input
              type="text"
              class="form-input"
              formControlName="username"
              [class.invalid]="loginForm.get('username')?.invalid && (loginForm.get('username')?.touched || submitted)"
            />
            <div *ngIf="loginForm.get('username')?.invalid && (loginForm.get('username')?.touched || submitted)"
                 class="error-message">
              <span *ngIf="loginForm.get('username')?.errors?.['required']">
                Username is required
              </span>

            </div>
          </div>

          <div class="form-group">
            <label class="form-label">Password</label>
            <input
              type="password"
              class="form-input"
              formControlName="password"
              [class.invalid]="loginForm.get('password')?.invalid && (loginForm.get('password')?.touched || submitted)"
            />
            <div *ngIf="loginForm.get('password')?.invalid && (loginForm.get('password')?.touched || submitted)"
                 class="error-message">
              <span *ngIf="loginForm.get('password')?.errors?.['required']">
                Password is required
              </span>
            </div>
          </div>

          <button class="btn btn-primary" type="submit">Sign In</button>
        </form>
        <p style="margin-top: 1rem">
          New User? <a class="link-text" routerLink="/signup">Create Account</a>
        </p>
      </div>
    </div>
  </div>
</div>

// TP6-React_Angular/react-auth-system/src/components/Login.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { login } from '../api/auth';
import logo from "../assets/enset_logo.png";

function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await login(username, password);
      localStorage.setItem('token', 'loggedIn');
      navigate('/dashboard');
    // eslint-disable-next-line no-unused-vars
    } catch (err) {
      setError('Invalid username or password');
    }
  };

return (
    <div className="auth-container">
      <div className="brand-section">
        <div className="brand-content">
          <img src={logo} alt="ENSET Logo" className="brand-logo" />
          <h1>ENSET</h1>
          <p>École Normale Supérieure de l'Enseignement Technique</p>
        </div>
      </div>
      
      <div className="form-section">
        <div className="auth-card">
          <div className="form-header">
          <img src={logo} alt="ENSET Logo" className="brand-logo" />
            <h2>User Login</h2>
          </div>
          <div className="form-body">
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                {error && <p className="error-message">{error}</p>}
                <br />
                <label className="form-label">Username</label>
                <input
                  type="text"
                  className="form-input"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label">Password</label>
                <input
                  type="password"
                  className="form-input"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button className="btn btn-primary" type="submit">Sign In</button>
            </form>
            <p style={{ marginTop: '1rem' }}>
              New User? <Link className="link-text" to="/signup">Create Account</Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Login;
