// TP6-React_Angular/angular-auth-system/src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, RouterLink],
})
export class SignupComponent {
  signupForm: FormGroup;
  errorMessage: string = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.signupForm = this.fb.group(
      {
        username: ['', [Validators.required]],
        password: ['', [Validators.required, Validators.minLength(6)]],
        confirmPassword: ['', Validators.required],
      },
      { validator: this.passwordMatchValidator }
    );
  }

  passwordMatchValidator(form: FormGroup) {
    return form.get('password')?.value === form.get('confirmPassword')?.value
      ? null
      : { mismatch: true };
  }

  onSubmit() {
    if (this.signupForm.valid) {
      const { username, password } = this.signupForm.value;
      this.authService.signup(username, password).subscribe({
        next: () => {
          this.router.navigate(['/login']);
        },
        error: () =>
          (this.errorMessage = 'Registration failed. Please try again.'),
      });
    }
  }
}

<div class="auth-container">
  <div class="brand-section">
    <div class="brand-content">
      <img src="assets/enset_logo.png" alt="ENSET Logo" class="brand-logo" />
      <h1>ENSET</h1>
      <p>École Normale Supérieure de l'Enseignement Technique</p>
    </div>
  </div>

  <div class="form-section">
    <div class="auth-card">
      <div class="form-header">
        <img src="assets/enset_logo.png" alt="ENSET Logo" class="brand-logo" />
        <h2>Create New Account</h2>
      </div>
      <div class="form-body">
        <div *ngIf="errorMessage" class="error-messag">{{ errorMessage }}</div>
        <form [formGroup]="signupForm" (ngSubmit)="onSubmit()">
          <div class="form-group">
            <label class="form-label">Username</label>
            <input
              type="text"
              class="form-input"
              formControlName="username"
              required
            />
            <div *ngIf="signupForm.get('username')?.errors?.['required'] &&
                      (signupForm.get('username')?.touched || signupForm.get('username')?.dirty)"
                 class="error-message">
              Username is required
            </div>
          </div>

          <div class="form-group">
            <label class="form-label">Password</label>
            <input
              type="password"
              class="form-input"
              formControlName="password"
              required
            />
            <div *ngIf="signupForm.get('password')?.errors?.['required'] &&
                      (signupForm.get('password')?.touched || signupForm.get('password')?.dirty)"
                 class="error-message">
              Password is required
            </div>
            <div *ngIf="signupForm.get('password')?.errors?.['minlength'] &&
                      (signupForm.get('password')?.touched || signupForm.get('password')?.dirty)"
                 class="error-message">
              Password must be at least 6 characters
            </div>
          </div>

          <div class="form-group">
            <label class="form-label">Confirm Password</label>
            <input
              type="password"
              class="form-input"
              formControlName="confirmPassword"
              required
            />
            <div *ngIf="signupForm.get('confirmPassword')?.errors?.['required'] &&
                      (signupForm.get('confirmPassword')?.touched || signupForm.get('confirmPassword')?.dirty)"
                 class="error-message">
              Confirm Password is required
            </div>
            <div *ngIf="signupForm.errors?.['mismatch'] &&
                      (signupForm.get('confirmPassword')?.touched || signupForm.get('confirmPassword')?.dirty)"
                 class="error-message">
              Passwords do not match
            </div>
          </div>

          <button class="btn btn-primary" type="submit" [disabled]="!signupForm.valid">Create Account</button>
        </form>
        <p style="margin-top: 1rem; text-align: center">
          Already registered? <a class="link-text" routerLink="/login">Login here</a>
        </p>
      </div>
    </div>
  </div>
</div>

// TP6-React_Angular/react-auth-system/src/components/Signup.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { signup } from '../api/auth';
import logo from "../assets/enset_logo.png";

function Signup() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    try {
      await signup(username, password);
      localStorage.setItem('token', 'loggedIn');
      navigate('/dashboard');
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div className="auth-container">
      <div className="brand-section">
        <div className="brand-content">
          <img src={logo} alt="ENSET Logo" className="brand-logo" />
          <h1>ENSET</h1>
          <p>École Normale Supérieure de l'Enseignement Technique</p>
        </div>
      </div>
      
      <div className="form-section">
        <div className="auth-card">
          <div className="form-header">
          <img src={logo} alt="ENSET Logo" className="brand-logo" />
            <h2>Create New Account</h2>
          </div>
          <div className="form-body">
            {error && <div className="error-message">{error}</div>}
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label className="form-label">Username</label>
                <input
                  type="text"
                  className="form-input"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label">Password</label>
                <input
                  type="password"
                  className="form-input"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label">Confirm Password</label>
                <input
                  type="password"
                  className="form-input"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  required
                />
              </div>
              <button className="btn btn-primary" type="submit">Create Account</button>
            </form>
            <p style={{ marginTop: '1rem', textAlign: 'center' }}>
              Already registered? <Link className="link-text" to="/login">Login here</Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Signup;
